
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miloEgon/chapter2
          search-paths: respo
          username: miloEgon
          password:
      label: master
  application:
    name: config-server
server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
